version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "4040:80"
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/nginx.conf
  node-app:
    build: .
    environment:
      - PORT=4040
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mateusz
      - MONGO_INITDB_ROOT_PASSWORD=haslo
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis

volumes:
  mongo-db:
